version: '3'

services:
#  app:
#    build: .
#    command: go run app/main.go
#    volumes:
#      - ./:/home/src/unio-logger
#    ports:
#      - '8080:8080'
#    depends_on:
#      - db
#    links:
#      - db

  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
